//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import clsx from 'clsx';

const inter = Inter(
  { subsets: ["latin"],
    display: 'swap',
    variable: '--font-inter',
  }
);

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/
// Use local version of Lexend so that we can use OpenType features
const lexend = localFont({
  src: '/fonts/lexend.woff2',
  display: 'swap',
  variable: '--font-lexend',
})

export const metadata = {
  title: {
    template: '%s - Docs',
    default: 'CacheAdvance - Never miss the cache again.',
  },
  description:
    'Cache every single thing your app could ever do ahead of time, so your code never even has to run at all.',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clsx('h-full antialiased', inter.variable, lexend.variable)} suppressHydrationWarning>
      <body className={inter.className}>{children}</body>
    </html>
  );
}


